### ISSUE TITLE
Improvement implemented XML and Raw Content now working save searches. 

### ISSUE THREAD

**Issue by SRFTInterface** [Robsodd/RDUH-Intersystems-HL7v2-Browser-Extension#1]
I have tweaked the searching in messagesearch.js to allow custom XML to work.
We search a lot by rawcontent in hl7 messages. Please see changes and see if you want to accept them it allows body types now 

if ((criterionType == "VDocPath") || (criterionType == "VDocSegment") || (criterionType == "Header")||(**criterionType == "Body"**)) {
[message_search.txt](https://github.com/user-attachments/files/16521174/message_search.txt)
 changed from js to .txt

**Comment by Robsodd** [comment]
Hi @SRFTInterface 

Thanks for using my extension! And for being brave enough to have a play. Apologies for the code, I assumed nobody would ever look...

Have you tested this?

I'd have thought that as Saved Searches mainly works in the criteria_cache.js file (I should probably rename the file to saved_searches.js) that you'd also have to edit the addCriteriaToSearch(clickedCriteria) function 

The problem is that I've had to make an assumption about which Criterion Type is being used based on the Class. If you see screenshots below you'll notice the Criterion Type isn't listed in the section of HTML that is saved in the saved searches, just the Class:

<img width="187" alt="image" src="https://github.com/user-attachments/assets/a888b899-3da4-4d01-9f07-6ddd9b55efb0">



So if you're searching RawContent over the Ens.Lib.HL7 Class then it'll currently assume the Criterion Type is set to VDocSegment Field - because when the Class is set to Ens.Lib.HL7 I assumed the Criterion Type would be VDocSegment.

<img width="475" alt="image" src="https://github.com/user-attachments/assets/286c310e-4db2-4cbf-9761-01db7df4f216">


It's a 1-2-1 mapping as there's no way of retrieving the Criterion Type from the HTML and you have to make an assumption about what Criterion Type to use.

I think the best change would be adding the following at line 453 of criteria_cache.js and just overwrite the criterionType if RawContent is found in the search value.

```
			// Change criterion Type assumption if RawContent present
			if ((row.cond_Val_1 == "RawContent")|| (row.cond_Val_2 == "RawContent")) {
				messageSearchEvent.criterionType = "Body";
			}
```

Testing this along side your changes seems to work:

<img width="507" alt="image" src="https://github.com/user-attachments/assets/a01bbbf6-e31e-40d9-8b1a-23542b59601a">

It's a bit hacky but so's this whole extension! If you have any ideas for how to improve it I'm all ears. 

I hope that makes sense and helps.

I have a couple other changes to add to a v1.9.1 so I'll put this in there
